### ISSUE TITLE
Doesn't work in FF 64.0

### ISSUE THREAD

**Issue by marki555** [timendum/proxy-reload#3] opened 2019-01-09 10:49 UTC
I have noticed that in FF 64 it doesn't work. It prints `<unavailable>` in the Browser console (black text on white background).

**Comment by timendum** [comment] 2019-01-10 09:22
Hi,
I'm not able to reproduce the error, can you clear the console, then press the button and then past here the full console content?

**Comment by marki555** [comment] 2019-01-10 12:48
It just prints that one line...
![proxy-reload-console](https://user-images.githubusercontent.com/7796878/50969302-500f8380-14de-11e9-8cf4-49d4d2cbd643.png)

Is there anything else I can try?

**Comment by mss** [comment] 2019-02-11 11:56
Same here, Firefox 65.0 on Ubuntu. The Browser Console just says:
```
12:49:43.916 <unavailable>
```

The string is maybe caused by e10s which broke `console.log` for addons if I understand [bug 1136995](https://bugzilla.mozilla.org/show_bug.cgi?id=1136995) right.

**Comment by timendum** [comment] 2019-02-11 16:38
Hi all,
thanks to your feedback I've released [Version 0.2.2](https://addons.mozilla.org/en-US/firefox/addon/reload-pac-button/), this will not fix the issue but hopefully it will provide better log in browser console.

Can you upgrade and check again?

**Comment by marki555** [comment] 2019-02-12 08:39
Hi,
here is result:
```
(proxy-reload) Error with http://example.com/ - Error: 0 is not a valid value for socksVersion. background.js:13:3

    refreshPac moz-extension://a315a9f6-5a5d-40ca-a9aa-743e5fa43d81/background.js:13 

(proxy-reload) Error with http://example.com/ -  {} background.js:14:3

    refreshPac moz-extension://a315a9f6-5a5d-40ca-a9aa-743e5fa43d81/background.js:14 
```

**Comment by mss** [comment] 2019-02-12 09:04
Mine is a bit different but generally the same (see below).

```
09:54:45.903
(proxy-reload) Error with http://example.com/ - Error: :80 is not a valid value for http. background.js:13:3

    refreshPac moz-extension://dfaca758-86bb-49c4-9863-0d0ecc922bbd/background.js:13 

09:54:45.904
(proxy-reload) Error with http://example.com/ -  {} background.js:14:3

    refreshPac moz-extension://dfaca758-86bb-49c4-9863-0d0ecc922bbd/background.js:14 
```

**Comment by mss** [comment] 2019-02-12 09:18
Hmmm… I think I can guess what the issue is and why the errors are different: I guess the `browser.proxy.settings.set({value: proxyConfig});` first validates all values of that [object](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings) even though it should ignore it due to `proxyType`. In my case I had a SOCKS proxy configured and @marki555 probably had something else or nothing at all. So the value of `socksVersion` is ok for me and the value for `http`, which seemingly defaults to `:80`, is ok for them.

Sounds like a Firefox bug to me unless I miss something.

**Comment by timendum** [comment] 2019-02-12 15:03
It's probably a Firefox bug, because resubmitting the same setting should not result in an error.

But as a workaround, I've released [Version 0.3](https://addons.mozilla.org/en-US/firefox/addon/reload-pac-button/), the addon now overwrite the settings if they are invalid.

I hope it works, I'm unable to reproduce the issue with my Firefox version, even I have incorrect settings, they are not a rejected on PAC reloading.

**Comment by marki555** [comment] 2019-02-12 15:08
Seems to work now:
```
(proxy-reload) Invalid proxy config found, overwriting (catched: Error: 0 is not a valid value for socksVersion.) background.js:7:9
(proxy-reload) Temp browserSettings true background.js:21:9
PAC file installed from http://localhost:81/proxy.php
```

**Comment by mss** [comment] 2019-02-12 19:30
Looks good here too. I also checked the `access.log` to see if the file was pulled.

```
20:26:53.728 PAC-alert: https://token.services.mozilla.com/ (52.10.60.207) -> DIRECT
20:26:53.997 (proxy-reload) Original config: {"proxyType":"autoConfig","autoConfigUrl":"http://localhost/pac/socks.pac","autoLogin":false,"proxyDNS":false,"httpProxyAll":false,"socksVersion":5,"passthrough":"localhost, 127.0.0.0/8, ::1","http":":80","ftp":"","ssl":"","socks":"198.18.0.122:1080"} background.js:3:5
20:26:54.002 (proxy-reload) Invalid proxy config found, overwriting (catched: Error: :80 is not a valid value for http.) background.js:7:9
20:26:54.012 (proxy-reload) Temp browserSettings true background.js:21:9
20:26:54.066 PAC file installed from http://localhost/pac/socks.pac
20:26:54.454 PAC-alert: https://sync-598-us-west-2.sync.services.mozilla.com/ (54.186.136.17) -> DIRECT
```

**Comment by timendum** [comment] 2019-02-14 16:13
Thanks for the feedback, I'm closing the issue.

**Closed as completed by timendum** 2019-02-14 16:13 UTC
